### ISSUE TITLE
Incompatible with other omniauth solutions since version 2.10.0

### ISSUE THREAD

**Issue by jonhue** [isaacsanders/omniauth-stripe-connect#44] opened 2017-02-01 18:40 UTC
Because this gem now depends on the newest version of the `omniauth-oauth2` gem (`1.4`), it raises an incompatibility issue if used together with other common omniauth authentication solutions like `omniauth-facebook`.

Source:

    Bundler could not find compatible versions for gem "omniauth-oauth2":
    In Gemfile:
    omniauth-facebook (~> 4.0) was resolved to 4.0.0, which depends on
    omniauth-oauth2 (~> 1.2)
    
    omniauth-google-oauth2 (~> 0.4.1) was resolved to 0.4.1, which depends on
    omniauth-oauth2 (>= 1.3.1)
       
    omniauth-slack (~> 2.3) was resolved to 2.3.0, which depends on
    omniauth-oauth2 (~> 1.3.1)
       
    omniauth-stripe-connect (~> 2.9) was resolved to 2.10.0, which depends on
    omniauth-oauth2 (~> 1.4)

    Failed to install gems via Bundler.

**Comment by jonhue** [comment] 2017-02-01 19:07
The Pull Request #45 should fix the issue.

**Comment by isaacsanders** [comment] 2017-04-10 14:13
@jonhue While I could make changes and back down the requirement, there is no good reason to.

If their software isn't compatible with the newest version, it would be better for them to loosen their requirements, or upgrade.

The gem with the problem is omniauth-slack, by using the `~>` operator with a fully declared version, they lock down to `>= 1.3.1` and `< 1.3.2`. Everything else is very permissive.

I would recommend opening an issue with them. I am closing this issue.

Source: http://guides.rubygems.org/patterns/#declaring-dependencies

**Closed by isaacsanders** 2017-04-10 14:13 UTC
